### PR TITLE
#Add Code_Of_Conduct.md

### LINKED ISSUE #33: (Documentation) Add code of conduct
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #33 

This PR addresses the addition of code of conduct markdown file for the users of Picwise.co repository. 

Please add level1 and gssoc-ext labels to this PR.

Thank you!

### CODE REVIEW

**Comment by KiranBaliga** [comment]
@Aryainguz Please review

**Comment by KiranBaliga** [comment]
@Aryainguz Please review and add level1 and gssoc-ext labels to this PR.

**Comment by KiranBaliga** [comment]
@Aryainguz please review the PR. Thanks

**Comment by KiranBaliga** [comment]
@Aryainguz I kindly request you to review the PR and assign relevant labels such as level1 & gssoc-ext to this PR. Thank you!

**Comment by Aryainguz** [comment]
sorry this isn't upto the mark

**Comment by KiranBaliga** [comment]
@Aryainguz okay! It was a genuine effort to do it. Anyways thanks for feedback.

**Pull request closed without merging**
